---
  .travis.yml:
    hc_secure: "ke8ypgybezHLwDyIBicM/3VfEuSsutIfMJ/C9BvhF/AM3/PWE7tiepR3/KKZ\nZrrF5BWpiNuY9kRXuD+cqfeKSymSoWi88ySd0Cpd8EagjXiGQxjS1by4kDEb\nyOpqHh9WUR5Ln8BBzXUDLjxgx45PurZrW05sx5rj+zmJO0a6n8U="

