---
  .travis.yml:
    hc_secure: "fJchCIXBsiv4Vt4Mjj2TG4xoumBoDtF/x++gPSWnX05f/+t7LJ11fxmhlyBgToUk/df8mbOglZSy0wuKZixGyvAZjEJQU7PEAYinzn/Oak86tGkJxWeIDHNbZigCacDRXpetHgSf2sBtItp8AXs11kch+FgXEL5+7tvUKNyd/w4="

